# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7acaeeb2806ce17ea2b4041429680898038dc10b23746ea670a85049062327be2bd8a40d8aa988f0a6779abef54dd8a951013c2db23161787afe9918096670c8

test:
  secret_key_base: fbb003029390faaa297bd5cd703ccf58079c03acde3c4a6d30af29b03c1abdea5b00a96d4550023a047bd12fd88d1151ee31b2a7b03718d50a083c980afd4fe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
